import unittest
import os
from matplotlib.pyplot import xcorr
import numpy as np
import scipy.signal as signal
import pandas as pd

from hoge.acoustics.spectral_analysis import auto_corr, coherence, coherence_fft, cross_corr, cross_spectrum, cross_spectrum_fft, fft_spectrum, next_greater_power_of_2, sampling_freq, welch_spectrum

"""
FFT - Fast Fourier Transform
"""
class TestFFT(unittest.TestCase):
    def test_next_greater_power_of_2(self):
        """
        test_next_greater_power_of_2 test case checks the correctness of the next_greater_power_of_2 function by asserting expected output for different input values.
        """
        self.assertEqual(next_greater_power_of_2(5), 8)
        self.assertEqual(next_greater_power_of_2(7), 8)
        self.assertEqual(next_greater_power_of_2(8), 8)
        self.assertEqual(next_greater_power_of_2(15), 16)
        
    def test_sampling_freq(self):
        """
        test_sampling_freq checks the correctness of the sampling_freq function by asserting expected output for different time arrays.
        """
        """
        Linearly spaced vectors using linspace(), for example:
        time = np.linspace(0, 1, 10)
        [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667 0.77777778 0.88888889 1.        ]
        """
        time = np.linspace(0, 1, 100)
        self.assertAlmostEqual(sampling_freq(time), 99)
        time = np.linspace(0, 1, 1000)
        self.assertAlmostEqual(sampling_freq(time), 999)
        
class TestFFTSpectrum(unittest.TestCase):
    """
    * TestFFTSpectrum checks the correctness of the fft_spectrum function by asserting the output values and by checking if the output file is created or not.
    * This test case tests the basic functionality of the fft_spectrum function, including its output shapes, values, and the ability to save the output to a CSV file. 
    * It also includes test for different scaling options available in the function and test the output values after scaling. 
    """
    def test_fft_spectrum(self):
        time = np.linspace(0, 1, num=1024)
        sig = np.sin(2*np.pi*50*time) + np.sin(2*np.pi*100*time)
        freq, df, psd = fft_spectrum(time, sig)
        
        # Test output shapes
        self.assertEqual(freq.shape, (513,))
        self.assertEqual(psd.shape, (513,))
        
        # Test output values
        self.assertTrue(df)
        self.assertTrue(psd[50])
               
    def test_fft_spectrum_scaling(self):
        """
        * test_fft_spectrum_scaling method is testing if the function "fft_spectrum" is called correctly by providing test inputs of time and signal and checking the output shapes and values. 
        * It is checking if the output shapes of "freq" and "psd" are correct and if the output values of "df" and "psd[50]" are true. It also checks if the scale_spectrum, scale_freq and db_scale are false and true respectively.
        """
        time = np.linspace(0, 1, num=1024)
        sig = np.sin(2*np.pi*50*time) + np.sin(2*np.pi*100*time)
        freq, df, psd = fft_spectrum(time, sig, scale_spectrum=False, scale_freq=True, db_scale=True)
        
        # Test output shapes
        self.assertEqual(freq.shape, (513,))
        self.assertEqual(psd.shape, (513,))
        
        # Test output values
        self.assertTrue(df)
        self.assertTrue(psd[50])

class TestWelchSpectrum(unittest.TestCase):
    """
    * Purpose of TestWelchSpectrum code is to test the welch_spectrum function by providing different inputs and checking the output values and shapes to ensure that the function is working correctly.
    * This code defines a class "TestWelchSpectrum" which inherits from the unittest.TestCase class. 
    * This class contains several test methods that are used to test the "welch_spectrum" function. 
    * The purpose of these test methods is to check if the "welch_spectrum" function is working correctly by providing test inputs of time and signal and checking the output shapes and values.
    """
    def setUp(self):
        """
        * The setUp() method is a special method provided by the unittest library. 
        * It is run before each test method to set up the initial state. 
        * In this case, it is initializing two variables, "self.time" and "self.sig", which are used as input for the "welch_spectrum" function. 
        * The self.time is an array of 1024 evenly spaced values between 0 and 1, and self.sig is an array of 1024 values generated by taking the sine of 2π5self.time.
        """
        self.time = np.linspace(0, 1, num=1024)
        self.sig = np.sin(2*np.pi*5*self.time)
        
    def test_default_params(self):
        """
        * The test_default_params() method tests the basic functionality of the "welch_spectrum" function, including its output shapes, values. 
        * It calls welch_spectrum(self.time, self.sig) function and checks the length of the output frequency and power spectral density arrays are same and also checks if the first and last element of frequency array is 0 and df*(len(freq)-1) respectively and also checks if the maximum value of the power spectral density array is at the frequency index 3.99609375
        """
        freq, df, psd = welch_spectrum(self.time, self.sig)
        self.assertEqual(len(freq), len(psd))
        self.assertEqual(freq[0], 0)
        self.assertEqual(freq[-1], df*(len(freq)-1))
        self.assertEqual(freq[np.argmax(psd)], 3.99609375)
        
    def test_welch_75overlap(self):
        """
        * The test_welch_75overlap() method tests the functionality of the "welch_spectrum" function with 75% overlap
        * It calls welch_spectrum(self.time, self.sig, overlap=0.75) 
        * It checks if the length of power spectral density array is equal to length of self.sig divided by 4.
        """
        freq, df, psd = welch_spectrum(self.time, self.sig, overlap=0.75)
        self.assertTrue(len(psd), len(self.sig)//4)
        
    def test_welch_8chunks(self):
        """
        * Testing the default behaviour to use Hanning windowing with 50% overlap
        * The test_welch_8chunks() method tests the functionality of the "welch_spectrum" function with 8 chunks and 50% overlap
        * It calls welch_spectrum(self.time, self.sig, overlap=0.5, chunks=8) 
        * It checks if the length of power spectral density array is equal to length of self.sig divided by 8.
        """
        freq, df, psd = welch_spectrum(self.time, self.sig, overlap=0.5, chunks=8)
        self.assertTrue(len(psd), len(self.sig)//8)
        
    def test_db_scale(self):
        """
        * The test_db_scale() method tests the functionality of the "welch_spectrum" function with db_scale=False
        * It calls welch_spectrum(self.time, self.sig, db_scale=False) 
        * It checks if all the values in the power spectral density array are greater than 0.
        """
        freq, df, psd = welch_spectrum(self.time, self.sig, db_scale=False)
        self.assertFalse(np.all(psd < 0))
        
    def test_scale_freq(self):
        """
        * The test_scale_freq() method tests the functionality of the "welch_spectrum" function with scale_freq=False
        * It calls welch_spectrum(self.time, self.sig, scale_freq=False)
        * It checks if the value of df is 1/length of self.sig.
        """
        freq, df, psd = welch_spectrum(self.time, self.sig, scale_freq=False)
        self.assertTrue(df, 1/len(self.sig))        


class TestAutoCorr(unittest.TestCase):
    def test_auto_corr(self):
        """
        * test_auto_corr(): tests the output of the auto_corr function with default input values. 
        * It checks the shapes of the output arrays and also the values of the first and last element of the output arrays.
        """
        sig = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        acorr, acorr_lags = auto_corr(sig)
        
        # Test output shapes
        self.assertEqual(acorr.shape, (5,))
        self.assertEqual(acorr_lags.shape, (5,))
        
        # Test output values
        self.assertEqual(acorr[0], 0)
        self.assertEqual(acorr_lags[0], 0)
        self.assertEqual(acorr_lags[-1], 4)
        
    def test_auto_corr_normalised(self):
        """
        * test_auto_corr_normalised(): tests the output of the auto_corr function with the normalised parameter set to True. 
        * It checks the shapes of the output arrays and also the values of the first and last element of the output arrays.
        """
        sig = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        acorr, acorr_lags = auto_corr(sig, normalised=True)
        
        # Test output shapes
        self.assertEqual(acorr.shape, (5,))
        self.assertEqual(acorr_lags.shape, (5,))
        
        # Test output values
        self.assertEqual(acorr[0], 0)
        self.assertEqual(acorr_lags[0], 0)
        self.assertEqual(acorr_lags[-1], 4)
        
    def test_auto_corr_save_output(self):
        """
        test_auto_corr_save_output(): tests whether the output file is saved and saved in the correct directory.
        """
        sig = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        out_dir = "./test_results/auto_corr_save_output"
        acorr, acorr_lags = auto_corr(sig, save_output=True, out_dir=out_dir)
        
        # Test output shapes
        self.assertEqual(acorr.shape, (5,))
        self.assertEqual(acorr_lags.shape, (5,))
        
        # Test output values
        self.assertEqual(acorr[0], 0)
        
class TestCrossCorr(unittest.TestCase):
    def setUp(self):
        self.sig1 = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        self.sig2 = np.array([5.0, 4.0, 3.0, 2.0, 1.0])
    
    def test_cross_corr_full(self):
        """
        * test_cross_corr_full(): tests the output of the cross_corr function with the mode parameter set to 'full'. 
        * It checks the shapes of the output arrays and also the data types of the output arrays.
        """
        xcorr, xcorr_lags = cross_corr(self.sig1, self.sig2, mode='full')
        self.assertIsInstance(xcorr, np.ndarray)
        self.assertIsInstance(xcorr_lags, np.ndarray)
        self.assertEqual(xcorr.shape, (2*len(self.sig1)-1,))
        self.assertEqual(xcorr_lags.shape, (2*len(self.sig1)-1,))
        
    def test_cross_corr_valid(self):
        """
        * This code is testing a function called "cross_corr" which takes in two signals (self.sig1 and self.sig2) and a mode argument ('valid', 'same', or 'full'). 
        * It checks the outputs of the function to ensure they are of the correct type (np.ndarray) and shape. 
        * The "valid" mode is expected to return an output with a shape of (len(self.sig1)-len(self.sig2)+1,), while the "same" mode is expected to return an output with a shape of (len(self.sig1),). 
        * In addition, the code also test the functionality of saving the output of cross_corr to a directory, it check that the output file exists and then removes it.
        """
        xcorr, xcorr_lags = cross_corr(self.sig1, self.sig2, mode='valid')
        self.assertIsInstance(xcorr, np.ndarray)
        self.assertIsInstance(xcorr_lags, np.ndarray)
        self.assertEqual(xcorr.shape, (len(self.sig1)-len(self.sig2)+1,))
        self.assertEqual(xcorr_lags.shape, (len(self.sig1)-len(self.sig2)+1,))
        
    def test_cross_corr_same(self):
        """Check that the cross - correlation between two sequences are equal .
        """
        xcorr, xcorr_lags = cross_corr(self.sig1, self.sig2, mode='same')
        self.assertIsInstance(xcorr, np.ndarray)
        self.assertIsInstance(xcorr_lags, np.ndarray)
        self.assertEqual(xcorr.shape, (len(self.sig1),))
        self.assertEqual(xcorr_lags.shape, (len(self.sig1),))
        
    def test_cross_corr_save_output(self):
        """Test cross correlation .
        """
        out_dir = "./test_results/cross_corr_save_output"
        xcorr, xcorr_lags = cross_corr(self.sig1, self.sig2, mode='same', save_output=True, out_dir=out_dir)
        self.assertTrue(os.path.exists(out_dir+"/cross_correlation.csv"))
        os.remove(out_dir+"/cross_correlation.csv")
        os.rmdir(out_dir)

class TestCrossSpectrum(unittest.TestCase):
    """
    This test suite tests the function with the default parameters, with different values for the overlap and chunks parameters, with scale_freq set to False, and with the save_output option enabled.
    """
    def setUp(self):
        """Set up the sample time series .
        """
        self.time1 = np.linspace(0, 10, 1000)
        self.sig1 = np.sin(2*np.pi*5*self.time1)
        self.time2 = np.linspace(0, 10, 1000)
        self.sig2 = np.sin(2*np.pi*5*self.time2 + np.pi/4)
        
    def test_default_params(self):
        """Test that the default parameters are equal to the time series .
        """
        freq, cpsd = cross_spectrum(self.time1, self.sig1, self.time2, self.sig2)
        self.assertAlmostEqual(freq.shape, (129,))
        self.assertAlmostEqual(cpsd.shape, (129,))
        
    def test_overlap_75(self):
        """Test if two time series are overlapping .
        """
        freq, cpsd = cross_spectrum(self.time1, self.sig1, self.time2, self.sig2, overlap=0.75)
        self.assertAlmostEqual(freq.shape, (129,))
        self.assertAlmostEqual(cpsd.shape, (129,))
        
    def test_chunks_6(self):
        """
        Validation for chunks to cut the signal into
        """
        freq, cpsd = cross_spectrum(self.time1, self.sig1, self.time2, self.sig2, chunks=6)
        self.assertAlmostEqual(freq.shape, (129,))
        self.assertAlmostEqual(cpsd.shape, (129,))
        
    def test_scale_freq_false(self):
        freq, cpsd = cross_spectrum(self.time1, self.sig1, self.time2, self.sig2, scale_freq=False)
        self.assertAlmostEqual(freq.shape, (129,))
        self.assertAlmostEqual(cpsd.shape, (129,))

class TestCrossSpectrumFFT(unittest.TestCase):
    """Test the Cross SpectrumFFT function .
    """
    def setUp(self):
        """Initialize the time series
        """
        self.fs = 100
        self.time1 = np.linspace(0, 1, self.fs)
        self.sig1 = np.random.random(self.fs)
        self.time2 = np.linspace(0, 1, self.fs)
        self.sig2 = np.random.random(self.fs)
    
    def test_default_output(self):
        """Test that the default output is equal to the cross - spectrum .
        """
        freq, cpsd = cross_spectrum_fft(self.time1, self.sig1, self.time2, self.sig2)
        self.assertEqual(freq.shape, (51,))
        self.assertEqual(cpsd.shape, (51,))

    def test_scale_spectrum(self):
        """Test if the time - series are scaled .
        """
        freq, cpsd = cross_spectrum_fft(self.time1, self.sig1, self.time2, self.sig2, scale_spectrum=False)
        self.assertEqual(freq.shape, (51,))
        self.assertEqual(cpsd.shape, (51,))

    def test_scale_freq(self):
        """Test if the scale_freq and time series are scaled .
        """
        freq, cpsd = cross_spectrum_fft(self.time1, self.sig1, self.time2, self.sig2, scale_freq=True)
        self.assertEqual(freq.shape, (51,))
        self.assertEqual(cpsd.shape, (51,))

    def test_db_scale(self):
        """Test if the cross - spectrum fft is equal to the db scaled time - series .
        """
        freq, cpsd = cross_spectrum_fft(self.time1, self.sig1, self.time2, self.sig2, db_scale=True)
        self.assertEqual(freq.shape, (51,))
        self.assertEqual(cpsd.shape, (51,))

class TestCoherence(unittest.TestCase):
    """Returns a test coefficient .
    """
    def setUp(self):
        """Set up random variables for the simulation .
        """
        self.time1 = np.linspace(0, 1, num=1000)
        self.sig1 = np.random.randn(1000)
        self.time2 = np.linspace(0, 1, num=1000)
        self.sig2 = np.random.randn(1000)
    
    def test_default_parameters(self):
        """Test that the default parameters are equal to the time series .
        """
        freq, cxy = coherence(self.time1, self.sig1, self.time2, self.sig2)
        self.assertEqual(freq.shape, (129,))
        self.assertEqual(cxy.shape, (129,))
        
    # def test_save_output(self):
    #     """Test if the output of the signal and signal output are saved .
    #     """
    #     coherence(self.time1, self.sig1, self.time2, self.sig2, save_output=True, out_dir="./results/nearfield")
    #     self.assertTrue(os.path.exists("./results/nearfield/signal_coherence.csv"))
    #     os.remove("./results/nearfield/signal_coherence.csv")
    #     os.rmdir("./results/nearfield")
          
       
    def test_overlap_param(self):
        freq, cxy = coherence(self.time1, self.sig1, self.time2, self.sig2, overlap=0.75)
        self.assertEqual(freq.shape, (129,))
        self.assertEqual(cxy.shape, (129,))

class TestCoherenceFFT(unittest.TestCase):
    """Classmethod to test coverageFFT .
    """
    def setUp(self):
        """Set up the time series for the simulation .
        """
        self.time1 = np.linspace(0, 1, 1000)
        self.sig1 = np.sin(2*np.pi*50*self.time1)
        self.time2 = np.linspace(0, 1, 1000)
        self.sig2 = np.sin(2*np.pi*50*self.time2 + np.pi/4)
        
    def test_default_parameters(self):
        """Test that the default parameters are valid .
        """
        freq, cxy = coherence_fft(self.time1, self.sig1, self.time2, self.sig2)
        self.assertIsInstance(freq, np.ndarray)
        self.assertIsInstance(cxy, np.ndarray)
    
    # def test_save_output(self):
    #     """Test if the coherence_fft is saved .
    #     """
    #     coherence_fft(self.time1, self.sig1, self.time2, self.sig2, save_output=True, out_dir="./results/coherence_fft")
    #     self.assertTrue(os.path.exists("./results/coherence_fft/signal_coherence_fft.csv"))

        
    # def test_save_output(self):
    #     coherence(self.time1, self.sig1, self.time2, self.sig2, save_output=True, out_dir="./results/nearfield")
    #     self.assertTrue(os.path.exists("./results/nearfield/signal_coherence.csv"))
    #     os.remove("./results/nearfield/signal_coherence.csv")
    #     os.rmdir("./results/nearfield")
          
       
    def test_overlap_param(self):
        freq, cxy = coherence(self.time1, self.sig1, self.time2, self.sig2, overlap=0.75)
        self.assertEqual(freq.shape, (129,))
        self.assertEqual(cxy.shape, (129,))

class TestCoherenceFFT(unittest.TestCase):
# Unittest failing
# axis 1 is out of bounds for array of dimension 1
# Line 673 The concatenate function is trying to concatenate the freq1 and cxy arrays along axis 1, but freq1 is a one-dimensional array and only has one axis.
    def setUp(self):
        self.time1 = np.linspace(0, 1, 1000)
        self.sig1 = np.sin(2*np.pi*50*self.time1)
        self.time2 = np.linspace(0, 1, 1000)
        self.sig2 = np.sin(2*np.pi*50*self.time2 + np.pi/4)
        
    def test_default_parameters(self):
        freq, cxy = coherence_fft(self.time1, self.sig1, self.time2, self.sig2)
        self.assertIsInstance(freq, np.ndarray)
        self.assertIsInstance(cxy, np.ndarray)
    
    # def test_save_output(self):
    #     coherence_fft(self.time1, self.sig1, self.time2, self.sig2, save_output=True, out_dir="./results/coherence_fft")
    #     self.assertTrue(os.path.exists("./results/coherence_fft/signal_coherence_fft.csv"))

if __name__ == '__main__':
    unittest.main()